### ISSUE TITLE
Allow .define to work on images

### ISSUE THREAD

**Issue by byxor** [sentriz/steely#139]
If a definition contains nothing but an image URL, I think the image should be uploaded when the definition is invoked.

**Comment by itsdoddsy** [comment]
![image](https://user-images.githubusercontent.com/23368872/33764742-b45ff622-dc0d-11e7-94dc-a0ae68afe9d2.png)

**Comment by byxor** [comment]
As far as I know, fbchat can't read images from the chat.

**Comment by itsdoddsy** [comment]
https://fbchat.readthedocs.io/en/master/_modules/fbchat/client.html#Client.fetchImageUrl

**Comment by byxor** [comment]
What is the `image_id` and where do you get it from?

Also, it seems inconvenient to require 2 messages to define an image. It introduces race conditions with other people in the chat.

**Comment by itsdoddsy** [comment]
i don't know pal i just [read the fucking docs](fbchat.rtfd.io)

**Comment by byxor** [comment]
Why bother when an easier solution is staring you in the face?

**Comment by iandioch** [comment]
fbchat can iterate backwards through the chat, but it's not done anywhere right now, and isn't really in the format of any of the steely comments, so would need more work. I'd say go for the same approach as the gex card images, which I think is what Brandon is proposing.

You can dirtily check if something is an image by just trying to load the image URL and posting it, and seeing if it throws an exception :)

**Comment by devoxel** [comment]
Well there is already `.define code name contents` so we could add `.define img name url` to the api

**Comment by byxor** [comment]
`code_name` and `image_name`?
Or are there 3 arguments?

**Comment by devoxel** [comment]
There's three arguments, check out `.help define`
