### ISSUE TITLE
​

### ISSUE THREAD

**Issue by byxor** [sentriz/steely#200]
:fire:
:eyes:
:nose:
:lips:

Congrats on reviving steely.

What account is it running on?

---

Isn't it neat how you can use zero-width characters in the issue names? It makes them unclickable haha.

https://codepen.io/chriscoyier/pen/iLKwm

**Comment by byxor** [comment]
Isn't it neat how you can use zero-width characters in the issue names? It makes them unclickable haha.

https://codepen.io/chriscoyier/pen/iLKwm

**Comment by sentriz** [comment]
thank you mister
it's Rob Collegeson now
and broken

fixing soon
