### ISSUE TITLE
Add permissions for .reload and .restart plugins

### ISSUE THREAD

**Issue by byxor** [sentriz/steely#67]
These commands can be abused by everybody who can send Reed a message. Let's add some permissions instead.

:hand: HALT! You can't do that here. :no_entry:

**Comment by sentriz** [comment]
thats gonna come with sep #1, with a `admin` boolean arg in the command decorator
eg
```
@command("mock", admin=True)
def mock(bot, author_id, arg_string, stdin):
    message = arg_string or stdin
    bot.send_message("hello") # just an extra message not related to the chain
    return mocked(message)    # sent as message or sent to next in the .command | .chain
```

**Comment by byxor** [comment]
I like it.

**Comment by sentriz** [comment]
thanks sam

**Comment by byxor** [comment]
Be warned: https://softwareengineering.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior

(Arbitrary Uncle BrandonBob post)

**Comment by sentriz** [comment]
hmm interesting, got any other ideas?

**Comment by byxor** [comment]
Yeah that's much nicer :heart:

**Comment by byxor** [comment]
@sentriz Just made `.restart` only work for him. Good egg.

**Comment by byxor** [comment]
@sentriz Also made `.reload` only work for him too.

Should we close this issue? It doesn't use any kind of `@admin` decorator, but it still does the job.
