### ISSUE TITLE
Fix output of '.define list'

### ISSUE THREAD

**Issue by byxor** [sentriz/steely#68]
Facebook added strikethrough formatting recently, and the output of this command displays incorrectly.

Example:
![image](https://user-images.githubusercontent.com/14977217/30348403-1bac5de8-9807-11e7-9c8b-a371edcf9144.png)

Consider putting the output in a code block to prevent this.

**Comment by izaakf** [comment]
Agree

**Comment by izaakf** [comment]
[PR](https://github.com/sentriz/steely/pull/72)

**Comment by izaakf** [comment]
resolved #72
